Uma abordagem de programação dinâmica para o Problema do Caixeiro Viajante (TSP), seguindo a ideia do algoritmo de Bellman-Held-Karp, que é mais eficiente do que a força bruta para instâncias maiores.

Parâmetros de benchmarking para comparar o desempenho dos algoritmos em termos de tempo de execução.

Dados fictícios para simular diferentes instâncias do TSP.

In [2]:
import heapq

In [3]:
import itertools
import time
import numpy as np

# Função para calcular a distância total de um percurso
def calcular_distancia(percurso, distancias):
    return sum(distancias[percurso[i]][percurso[i + 1]] for i in range(len(percurso) - 1))

# Abordagem de Força Bruta
def tsp_forca_bruta(distancias):
    n = len(distancias)
    percursos = itertools.permutations(range(n))
    min_percurso, min_distancia = min(((p, calcular_distancia(p + (p[0],), distancias)) for p in percursos), key=lambda x: x[1])
    return min_percurso, min_distancia

# Abordagem de Programação Dinâmica (Bellman-Held-Karp)
def tsp_bellman_held_karp(distancias):
    n = len(distancias)
    C = {}
    for k in range(1, n):
        C[(1 << k, k)] = (distancias[0][k], 0)
    for s in range(2, n):
        for S in [frozenset(C) | {0} for C in itertools.combinations(range(1, n), s)]:
            bits = 0
            for bit in S:
                bits |= 1 << bit
            for k in S - {0}:
                prev = [(C[(bits ^ (1 << k), m)][0] + distancias[m][k], m) for m in S if m != 0 and m != k]
                C[(bits, k)] = min(prev)
    bits = (2**n - 1) - 1
    min_cost, parent = min([(C[(bits, k)][0] + distancias[k][0], k) for k in range(1, n)])
    percurso = [0]
    while parent != 0:
        percurso.append(parent)
        new_bits = bits ^ (1 << parent)
        _, parent = C[(bits, parent)]
        bits = new_bits
    percurso.append(0)
    return percurso, min_cost
    bits = (2**n - 1) - 1
    min_cost, parent = min([(C[(bits, k)][0] + distancias[k][0], k) for k in range(1, n)])
    percurso = [0]
    while parent != 0:
        percurso.append(parent)
        new_bits = bits ^ (1 << parent)
        _, parent = C[(bits, parent)]
        bits = new_bits
    percurso.append(0)
    return percurso, min_cost

# Gerando dados fictícios
np.random.seed(42)  # Para reprodutibilidade
n_cidades = 5
distancias = np.random.randint(1, 100, size=(n_cidades, n_cidades))
np.fill_diagonal(distancias, 0)
print("Matriz de Distâncias:\n", distancias)

# Benchmarking
inicio = time.time()
percurso, distancia = tsp_forca_bruta(distancias)
print(f"Força Bruta: Percurso: {percurso}, Distância: {distancia}, Tempo: {time.time() - inicio:.4f} segundos")

inicio = time.time()
percurso, distancia = tsp_bellman_held_karp(distancias)
print(f"Bellman-Held-Karp: Percurso: {percurso}, Distância: {distancia}, Tempo: {time.time() - inicio:.4f} segundos")


Matriz de Distâncias:
 [[ 0 93 15 72 61]
 [21  0 87 75 75]
 [88 24  0 22 53]
 [ 2 88 30  0  2]
 [64 60 21 33  0]]
Força Bruta: Percurso: (0, 2, 3, 4, 1), Distância: 120, Tempo: 0.0006 segundos


KeyError: (5, 2)

In [4]:
inicio = time.time()
percurso, distancia = tsp_bellman_held_karp(distancias)
print(f"Bellman-Held-Karp: Percurso: {percurso}, Distância: {distancia}, Tempo: {time.time() - inicio:.4f} segundos")

KeyError: (5, 2)